name: Unzip File

on:
  workflow_dispatch:  # يسمح بتشغيل الـ Workflow يدويًا

jobs:
  unzip:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        - uses: actions/checkout@v3
        
      - name: List contents of ZIP file
        run: unzip -l plugins.zip
        
      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Unzipped bot files" || echo "No changes to commit"
          git push || echo "No changes to push"
